module.exports =  [
    {name: 'apple', color: 'green', size: 'medium', type: 'fruit', hardness: 'medium'},
    {name: 'apple', color: 'red', size: 'medium', type: 'fruit', hardness: 'medium'},
    {name: 'lemon', color: 'yellow', size: 'medium', type: 'fruit', hardness: 'hard'},
    {name: 'banana', color: 'yellow', size: 'medium', type: 'fruit', hardness: 'medium'},
    {name: 'grape', color: 'white', size: 'small', type: 'fruit', hardness: 'soft'},
    {name: 'grape', color: 'green', size: 'small', type: 'fruit', hardness: 'soft'},
    {name: 'grape', color: 'black', size: 'small', type: 'fruit', hardness: 'soft'},
    {name: 'strawberry', color: 'red', size: 'small', type: 'fruit', hardness: 'soft'},
    {name: 'peach', color: 'orange', size: 'medium', type: 'fruit', hardness: 'medium'},
    {name: 'watermelon', color: 'green', size: 'big', type: 'fruit', hardness: 'hard'},
    {name: 'coconout', color: 'brown', size: 'big', type: 'fruit', hardness: 'hard'},
    {name: 'orange', color: 'orange', size: 'big', type: 'fruit', hardness: 'hard'},
    {name: 'cucumber', color: 'green', size: 'medium', type: 'vegetable', hardness: 'hard'},
    {name: 'onion', color: 'yellow', size: 'medium', type: 'vegetable', hardness: 'hard'},
    {name: 'garlic', color: 'white', size: 'small', type: 'vegetable', hardness: 'hard'},
    {name: 'carrot', color: 'orange', size: 'medium', type: 'vegetable', hardness: 'hard'},
    {name: 'cabbage', color: 'green', size: 'big', type: 'vegetable', hardness: 'hard'},
    {name: 'radish', color: 'red', size: 'small', type: 'vegetable', hardness: 'hard'},
    {name: 'pepper', color: 'yellow', size: 'medium', type: 'vegetable', hardness: 'medium'},
    {name: 'pepper', color: 'red', size: 'medium', type: 'vegetable', hardness: 'medium'},
    {name: 'broccoli', color: 'green', size: 'big', type: 'vegetable', hardness: 'medium'},
    {name: 'potato', color: 'brown', size: 'medium', type: 'vegetable', hardness: 'hard'},
    {name: 'pumpkin', color: 'orange', size: 'big', type: 'vegetable', hardness: 'hard'},
    {name: 'mushroom', color: 'white', size: 'small', type: 'vegetable', hardness: 'soft'},
  ];
