module.exports =  [
    {name: 'apple', color: 'green', size: 'medium', type: 'fruit', hardness: 'standard', stockId: 0},
    {name: 'apple', color: 'red', size: 'medium', type: 'fruit', hardness: 'standard', stockId: 0},
    {name: 'lemon', color: 'yellow', size: 'medium', type: 'fruit', hardness: 'hard', stockId: 1},
    {name: 'banana', color: 'yellow', size: 'medium', type: 'fruit', hardness: 'standard', stockId: 2},
    {name: 'grape', color: 'white', size: 'small', type: 'fruit', hardness: 'soft', stockId: 3},
    {name: 'grape', color: 'green', size: 'small', type: 'fruit', hardness: 'soft', stockId: 3},
    {name: 'grape', color: 'black', size: 'small', type: 'fruit', hardness: 'soft', stockId: 3},
    {name: 'strawberry', color: 'red', size: 'small', type: 'fruit', hardness: 'soft', stockId: 4},
    {name: 'peach', color: 'orange', size: 'medium', type: 'fruit', hardness: 'standard', stockId: 5},
    {name: 'watermelon', color: 'green', size: 'big', type: 'fruit', hardness: 'hard', stockId: 6},
    {name: 'coconout', color: 'brown', size: 'big', type: 'fruit', hardness: 'hard', stockId: 7},
    {name: 'orange', color: 'orange', size: 'big', type: 'fruit', hardness: 'hard', stockId: 8},
    {name: 'cucumber', color: 'green', size: 'medium', type: 'vegetable', hardness: 'hard', stockId: 9},
    {name: 'onion', color: 'yellow', size: 'medium', type: 'vegetable', hardness: 'hard', stockId: 10},
    {name: 'garlic', color: 'white', size: 'small', type: 'vegetable', hardness: 'hard', stockId: 11},
    {name: 'carrot', color: 'orange', size: 'medium', type: 'vegetable', hardness: 'hard', stockId: 12},
    {name: 'cabbage', color: 'green', size: 'big', type: 'vegetable', hardness: 'hard', stockId: 13},
    {name: 'radish', color: 'red', size: 'small', type: 'vegetable', hardness: 'hard', stockId: 14},
    {name: 'pepper', color: 'yellow', size: 'medium', type: 'vegetable', hardness: 'standard', stockId: 15},
    {name: 'pepper', color: 'red', size: 'medium', type: 'vegetable', hardness: 'standard', stockId: 15},
    {name: 'broccoli', color: 'green', size: 'big', type: 'vegetable', hardness: 'standard', stockId: 16},
    {name: 'potato', color: 'brown', size: 'medium', type: 'vegetable', hardness: 'hard', stockId: 17},
    {name: 'pumpkin', color: 'orange', size: 'big', type: 'vegetable', hardness: 'hard', stockId: 18},
    {name: 'mushroom', color: 'white', size: 'small', type: 'vegetable', hardness: 'soft', stockId: 19},
  ];
